CREATE DATABASE Customer_Analysis;
USE Customer_Analysis;
SELECT * FROM customer_shopping_behavior_cleaned;

--  1 What is the total revenue generated by male vs female customers ?
SELECT gender, SUM(purchase_amount) AS Total_revenue
FROM customer_shopping_behavior_cleaned
GROUP BY gender;

-- 2 Which customers used a discount but still spent more than the average purchase amount ?
SELECT customer_id, purchase_amount
FROM customer_shopping_behavior_cleaned
WHERE discount_applied = 'Yes' and purchase_amount >= (
SELECT AVG(purchase_amount)
 from customer_shopping_behavior_cleaned) ;
 
--  3 Which are the top 5 prodect with the highest average review rating ?
SELECT item_purchased, AVG(review_rating) AS 'Average Product Rating'
FROM  customer_shopping_behavior_cleaned
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
limit 5;

-- 4 Compare the average purchase amount between standard and express shipping ?
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer_shopping_behavior_cleaned
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- 5 Do subscribed customer spend more? compare average spend and total revenue betweem subscribes and non subscibes
select subscription_status,
COUNT(customer_id) AS Total_Customers,
ROUND (AVG(purchase_amount),2) AS avg_spend,
ROUND (SUM(purchase_amount),2) AS total_revenue
from customer_shopping_behavior_cleaned
group by subscription_status
order by total_revenue, avg_spend desc;

-- 6 which 5 products have the highest percentage of purchase with discount applied?
SELECT 
    item_purchased,
    ROUND(
        SUM(CASE 
            WHEN discount_applied = 'Yes' THEN 1 
            ELSE 0 
        END) / COUNT(*) * 100, 2
    ) AS discount_rate
FROM customer_shopping_behavior_cleaned
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7 Segment customers into new Returing and loyal based on their total number of previous purchases and show the count of each segment
SELECT
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(DISTINCT customer_id) AS customer_count
FROM customer_shopping_behavior_cleaned
GROUP BY customer_segment;

-- 8 What are the most 5 purchased product within each category
WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer_shopping_behavior_cleaned
    GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM product_counts
WHERE rn <= 5
ORDER BY category, purchase_count DESC;

-- 9 Are customers who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
SELECT
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribed_customers,
    ROUND(
        SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*) * 100,
        2
    ) AS subscription_rate
FROM customer_shopping_behavior_cleaned
GROUP BY customer_type;

-- 10 What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 /
        (SELECT SUM(purchase_amount)
         FROM customer_shopping_behavior_cleaned),
        2
    ) AS revenue_contribution
FROM customer_shopping_behavior_cleaned
GROUP BY age_group
ORDER BY revenue_contribution DESC;



 

